#!/usr/bin/env bash

# Convenience script to run the etherspot binary from built source
#
# ./skandha --redirectRpc

node --experimental-specifier-resolution=node ./packages/cli/bin/skandha.js start "$@"