#!/usr/bin/env bash

# Convenience script to run the etherspot binary from built source
#
# ./etherspot --network goerli

node --experimental-specifier-resolution=node --trace-deprecation --max-old-space-size=4096 ./packages/cli/bin/skandha.js start "$@"