import { ByteVectorType, UintNumberType, UintBigintType, BooleanType } from "@chainsafe/ssz";
export declare const Boolean: BooleanType;
export declare const Byte: UintNumberType;
export declare const Bytes4: ByteVectorType;
export declare const Bytes8: ByteVectorType;
export declare const Bytes20: ByteVectorType;
export declare const Bytes32: ByteVectorType;
export declare const Bytes48: ByteVectorType;
export declare const Bytes96: ByteVectorType;
export declare const Uint8: UintNumberType;
export declare const Uint16: UintNumberType;
export declare const Uint32: UintNumberType;
export declare const UintNum64: UintNumberType;
export declare const UintNumInf64: UintNumberType;
export declare const UintBn64: UintBigintType;
export declare const UintBn128: UintBigintType;
export declare const UintBn256: UintBigintType;
export declare const Version: ByteVectorType;
export declare const Address: ByteVectorType;
export declare const Signature: ByteVectorType;
//# sourceMappingURL=sszTypes.d.ts.map