/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../../common";

export interface BNPairingPrecompileCostEstimatorInterface
  extends utils.Interface {
  functions: {
    "baseCost()": FunctionFragment;
    "getGasCost(uint256)": FunctionFragment;
    "perPairCost()": FunctionFragment;
    "run()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "baseCost" | "getGasCost" | "perPairCost" | "run"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "baseCost", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGasCost",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "perPairCost",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "run", values?: undefined): string;

  decodeFunctionResult(functionFragment: "baseCost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGasCost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "perPairCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;

  events: {};
}

export interface BNPairingPrecompileCostEstimator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BNPairingPrecompileCostEstimatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    baseCost(overrides?: CallOverrides): Promise<[BigNumber]>;

    getGasCost(
      pairCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    perPairCost(overrides?: CallOverrides): Promise<[BigNumber]>;

    run(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  baseCost(overrides?: CallOverrides): Promise<BigNumber>;

  getGasCost(
    pairCount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  perPairCost(overrides?: CallOverrides): Promise<BigNumber>;

  run(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    baseCost(overrides?: CallOverrides): Promise<BigNumber>;

    getGasCost(
      pairCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    perPairCost(overrides?: CallOverrides): Promise<BigNumber>;

    run(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    baseCost(overrides?: CallOverrides): Promise<BigNumber>;

    getGasCost(
      pairCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    perPairCost(overrides?: CallOverrides): Promise<BigNumber>;

    run(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    baseCost(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGasCost(
      pairCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    perPairCost(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    run(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
