/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  UserOperationLib,
  UserOperationLibInterface,
} from "../../core/UserOperationLib";

const _abi = [
  {
    inputs: [],
    name: "PAYMASTER_DATA_OFFSET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAYMASTER_POSTOP_GAS_OFFSET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAYMASTER_VALIDATION_GAS_OFFSET",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a9610039600b82828239805160001a60731461002c57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c806325093e1b14604c578063b29a8ff4146065578063ede3150214606c575b600080fd5b6053602481565b60405190815260200160405180910390f35b6053601481565b605360348156fea26469706673582212201f7a90647e46dab09f0fa420d36a18b554361fc1351ea9b36329880cdbd465a364736f6c63430008170033";

type UserOperationLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UserOperationLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UserOperationLib__factory extends ContractFactory {
  constructor(...args: UserOperationLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<UserOperationLib> {
    return super.deploy(overrides || {}) as Promise<UserOperationLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UserOperationLib {
    return super.attach(address) as UserOperationLib;
  }
  override connect(signer: Signer): UserOperationLib__factory {
    return super.connect(signer) as UserOperationLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UserOperationLibInterface {
    return new utils.Interface(_abi) as UserOperationLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UserOperationLib {
    return new Contract(address, _abi, signerOrProvider) as UserOperationLib;
  }
}
