/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISenderCreator,
  ISenderCreatorInterface,
} from "../../interfaces/ISenderCreator";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initCode",
        type: "bytes",
      },
    ],
    name: "createSender",
    outputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "initCallData",
        type: "bytes",
      },
    ],
    name: "initEip7702Sender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISenderCreator__factory {
  static readonly abi = _abi;
  static createInterface(): ISenderCreatorInterface {
    return new utils.Interface(_abi) as ISenderCreatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISenderCreator {
    return new Contract(address, _abi, signerOrProvider) as ISenderCreator;
  }
}
