export const _abi = [
	{
		inputs: [
			{ internalType: 'address', name: '_owner', type: 'address' },
			{
				internalType: 'contract IEntryPoint',
				name: '_entryPoint',
				type: 'address',
			},
			{
				internalType: 'address',
				name: '_verifyingSigner',
				type: 'address',
			},
		],
		stateMutability: 'payable',
		type: 'constructor',
	},
	{ inputs: [], name: 'CanNotWithdrawToZeroAddress', type: 'error' },
	{ inputs: [], name: 'CannotBeUnrealisticValue', type: 'error' },
	{ inputs: [], name: 'DEXRouterCannotBeZero', type: 'error' },
	{ inputs: [], name: 'DepositCanNotBeZero', type: 'error' },
	{ inputs: [], name: 'ECDSAInvalidSignature', type: 'error' },
	{
		inputs: [{ internalType: 'uint256', name: 'length', type: 'uint256' }],
		name: 'ECDSAInvalidSignatureLength',
		type: 'error',
	},
	{
		inputs: [{ internalType: 'bytes32', name: 's', type: 'bytes32' }],
		name: 'ECDSAInvalidSignatureS',
		type: 'error',
	},
	{ inputs: [], name: 'EntryPointCannotBeZero', type: 'error' },
	{ inputs: [], name: 'FeeReceiverCannotBeZero', type: 'error' },
	{ inputs: [], name: 'NativeTokenBalanceZero', type: 'error' },
	{ inputs: [], name: 'NativeTokensWithdrawalFailed', type: 'error' },
	{
		inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
		name: 'OwnableInvalidOwner',
		type: 'error',
	},
	{
		inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
		name: 'OwnableUnauthorizedAccount',
		type: 'error',
	},
	{ inputs: [], name: 'OwnerCannotBeZero', type: 'error' },
	{ inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
	{ inputs: [], name: 'TokensAndAmountsLengthMismatch', type: 'error' },
	{ inputs: [], name: 'VerifyingSignerCannotBeZero', type: 'error' },
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'uint256',
				name: '_oldThresholdCost',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: '_newThresholdCost',
				type: 'uint256',
			},
			{
				indexed: true,
				internalType: 'address',
				name: '_actor',
				type: 'address',
			},
		],
		name: 'EPGasThresholdChange',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: '_oldfeeReceiver',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: '_newfeeReceiver',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: '_actor',
				type: 'address',
			},
		],
		name: 'FeeReceiverChanged',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'previousOwner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'newOwner',
				type: 'address',
			},
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'sender',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'value',
				type: 'uint256',
			},
		],
		name: 'Received',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'sender',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'token',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'totalCharge',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'address',
				name: 'oracleAggregator',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint32',
				name: 'priceMarkup',
				type: 'uint32',
			},
			{
				indexed: false,
				internalType: 'bytes32',
				name: 'userOpHash',
				type: 'bytes32',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'exchangeRate',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'enum MultiTokenPaymaster.ExchangeRateSource',
				name: 'priceSource',
				type: 'uint8',
			},
		],
		name: 'TokenPaymasterOperation',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'token',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'account',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'charge',
				type: 'uint256',
			},
		],
		name: 'TokenPaymentDue',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: '_oldSigner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: '_newSigner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: '_actor',
				type: 'address',
			},
		],
		name: 'VerifyingSignerChanged',
		type: 'event',
	},
	{
		inputs: [],
		name: 'UNACCOUNTED_COST',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint32', name: 'unstakeDelaySec', type: 'uint32' },
		],
		name: 'addStake',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'deposit',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'entryPoint',
		outputs: [
			{ internalType: 'contract IEntryPoint', name: '', type: 'address' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'feeReceiver',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'getDeposit',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{
						internalType: 'address',
						name: 'sender',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'nonce', type: 'uint256' },
					{ internalType: 'bytes', name: 'initCode', type: 'bytes' },
					{ internalType: 'bytes', name: 'callData', type: 'bytes' },
					{
						internalType: 'bytes32',
						name: 'accountGasLimits',
						type: 'bytes32',
					},
					{
						internalType: 'uint256',
						name: 'preVerificationGas',
						type: 'uint256',
					},
					{
						internalType: 'bytes32',
						name: 'gasFees',
						type: 'bytes32',
					},
					{
						internalType: 'bytes',
						name: 'paymasterAndData',
						type: 'bytes',
					},
					{ internalType: 'bytes', name: 'signature', type: 'bytes' },
				],
				internalType: 'struct PackedUserOperation',
				name: 'userOp',
				type: 'tuple',
			},
			{
				internalType: 'enum MultiTokenPaymaster.ExchangeRateSource',
				name: 'priceSource',
				type: 'uint8',
			},
			{ internalType: 'uint48', name: 'validUntil', type: 'uint48' },
			{ internalType: 'uint48', name: 'validAfter', type: 'uint48' },
			{ internalType: 'address', name: 'feeToken', type: 'address' },
			{
				internalType: 'address',
				name: 'oracleAggregator',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'exchangeRate', type: 'uint256' },
			{ internalType: 'uint32', name: 'priceMarkup', type: 'uint32' },
		],
		name: 'getHash',
		outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'owner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'bytes', name: 'paymasterAndData', type: 'bytes' },
		],
		name: 'parsePaymasterAndData',
		outputs: [
			{
				internalType: 'enum MultiTokenPaymaster.ExchangeRateSource',
				name: 'priceSource',
				type: 'uint8',
			},
			{ internalType: 'uint48', name: 'validUntil', type: 'uint48' },
			{ internalType: 'uint48', name: 'validAfter', type: 'uint48' },
			{ internalType: 'address', name: 'feeToken', type: 'address' },
			{
				internalType: 'address',
				name: 'oracleAggregator',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'exchangeRate', type: 'uint256' },
			{ internalType: 'uint32', name: 'priceMarkup', type: 'uint32' },
			{ internalType: 'bytes', name: 'signature', type: 'bytes' },
		],
		stateMutability: 'pure',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'enum IPaymaster.PostOpMode',
				name: 'mode',
				type: 'uint8',
			},
			{ internalType: 'bytes', name: 'context', type: 'bytes' },
			{ internalType: 'uint256', name: 'actualGasCost', type: 'uint256' },
			{
				internalType: 'uint256',
				name: 'actualUserOpFeePerGas',
				type: 'uint256',
			},
		],
		name: 'postOp',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'renounceOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_newFeeReceiver',
				type: 'address',
			},
		],
		name: 'setFeeReceiver',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'uint256',
				name: '_newThresholdCost',
				type: 'uint256',
			},
		],
		name: 'setUnaccountedEPGasThreshold',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_newVerifyingSigner',
				type: 'address',
			},
		],
		name: 'setVerifyingSigner',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'newOwner', type: 'address' },
		],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'unlockStake',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				components: [
					{
						internalType: 'address',
						name: 'sender',
						type: 'address',
					},
					{ internalType: 'uint256', name: 'nonce', type: 'uint256' },
					{ internalType: 'bytes', name: 'initCode', type: 'bytes' },
					{ internalType: 'bytes', name: 'callData', type: 'bytes' },
					{
						internalType: 'bytes32',
						name: 'accountGasLimits',
						type: 'bytes32',
					},
					{
						internalType: 'uint256',
						name: 'preVerificationGas',
						type: 'uint256',
					},
					{
						internalType: 'bytes32',
						name: 'gasFees',
						type: 'bytes32',
					},
					{
						internalType: 'bytes',
						name: 'paymasterAndData',
						type: 'bytes',
					},
					{ internalType: 'bytes', name: 'signature', type: 'bytes' },
				],
				internalType: 'struct PackedUserOperation',
				name: 'userOp',
				type: 'tuple',
			},
			{ internalType: 'bytes32', name: 'userOpHash', type: 'bytes32' },
			{ internalType: 'uint256', name: 'maxCost', type: 'uint256' },
		],
		name: 'validatePaymasterUserOp',
		outputs: [
			{ internalType: 'bytes', name: 'context', type: 'bytes' },
			{
				internalType: 'uint256',
				name: 'validationData',
				type: 'uint256',
			},
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'verifyingSigner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'dest', type: 'address' }],
		name: 'withdrawAllNative',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'contract IERC20', name: 'token', type: 'address' },
			{ internalType: 'address', name: 'target', type: 'address' },
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
		],
		name: 'withdrawERC20',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'contract IERC20', name: 'token', type: 'address' },
			{ internalType: 'address', name: 'target', type: 'address' },
		],
		name: 'withdrawERC20Full',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20[]',
				name: 'token',
				type: 'address[]',
			},
			{ internalType: 'address', name: 'target', type: 'address' },
			{ internalType: 'uint256[]', name: 'amount', type: 'uint256[]' },
		],
		name: 'withdrawMultipleERC20',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20[]',
				name: 'token',
				type: 'address[]',
			},
			{ internalType: 'address', name: 'target', type: 'address' },
		],
		name: 'withdrawMultipleERC20Full',
		outputs: [],
		stateMutability: 'payable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address payable',
				name: 'withdrawAddress',
				type: 'address',
			},
		],
		name: 'withdrawStake',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address payable',
				name: 'withdrawAddress',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'amount', type: 'uint256' },
		],
		name: 'withdrawTo',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{ stateMutability: 'payable', type: 'receive' },
] as const;
