/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iEntryPoint06Sol from "./IEntryPoint06.sol";
export type { iEntryPoint06Sol };
export type { IAccount06 } from "./IAccount06";
export type { IAggregator06 } from "./IAggregator06";
export type { INonceManager06 } from "./INonceManager06";
export type { IPaymaster06 } from "./IPaymaster06";
export type { IStakeManager06 } from "./IStakeManager06";
