import { ValueOf } from "@chainsafe/ssz";
import * as ssz from "./sszTypes.js";
export declare type Bytes4 = ValueOf<typeof ssz.Bytes4>;
export declare type Bytes8 = ValueOf<typeof ssz.Bytes8>;
export declare type Bytes20 = ValueOf<typeof ssz.Bytes20>;
export declare type Bytes32 = ValueOf<typeof ssz.Bytes32>;
export declare type Bytes48 = ValueOf<typeof ssz.Bytes48>;
export declare type Bytes96 = ValueOf<typeof ssz.Bytes96>;
export declare type Uint8 = ValueOf<typeof ssz.Uint8>;
export declare type Uint16 = ValueOf<typeof ssz.Uint16>;
export declare type Uint32 = ValueOf<typeof ssz.Uint32>;
export declare type UintNum64 = ValueOf<typeof ssz.UintNum64>;
export declare type UintNumInf64 = ValueOf<typeof ssz.UintNumInf64>;
export declare type UintBn64 = ValueOf<typeof ssz.UintBn64>;
export declare type UintBn128 = ValueOf<typeof ssz.UintBn128>;
export declare type UintBn256 = ValueOf<typeof ssz.UintBn256>;
export declare type Version = Bytes4;
export declare type Address = Bytes20;
export declare type Signature = Bytes96;
//# sourceMappingURL=types.d.ts.map