export const CustomRPCMethods = {
  skandha_validateUserOperation: "skandha_validateUserOperation",
  skandha_getGasPrice: "skandha_getGasPrice",
  skandha_config: "skandha_config",
  skandha_feeHistory: "skandha_feeHistory",
};

export const BundlerRPCMethods = {
  eth_chainId: "eth_chainId",
  eth_supportedEntryPoints: "eth_supportedEntryPoints",
  eth_sendUserOperation: "eth_sendUserOperation",
  eth_estimateUserOperationGas: "eth_estimateUserOperationGas",
  eth_getUserOperationReceipt: "eth_getUserOperationReceipt",
  eth_getUserOperationByHash: "eth_getUserOperationByHash",
  web3_clientVersion: "web3_clientVersion",
  debug_bundler_clearState: "debug_bundler_clearState",
  debug_bundler_dumpMempool: "debug_bundler_dumpMempool",
  debug_bundler_setReputation: "debug_bundler_setReputation",
  debug_bundler_dumpReputation: "debug_bundler_dumpReputation",
  debug_bundler_setBundlingMode: "debug_bundler_setBundlingMode",
  debug_bundler_setBundleInterval: "debug_bundler_setBundleInterval",
  debug_bundler_sendBundleNow: "debug_bundler_sendBundleNow",
};

export const RedirectedRPCMethods = {
  web3_sha3: "web3_sha3",
  net_version: "net_version",
  net_listening: "net_listening",
  net_peerCount: "net_peerCount",
  eth_protocolVersion: "eth_protocolVersion",
  eth_gasPrice: "eth_gasPrice",
  eth_blockNumber: "eth_blockNumber",
  eth_getBalance: "eth_getBalance",
  eth_getStorageAt: "eth_getStorageAt",
  eth_getTransactionCount: "eth_getTransactionCount",
  eth_getBlockTransactionCountByHash: "eth_getBlockTransactionCountByHash",
  eth_getBlockTransactionCountByNumber: "eth_getBlockTransactionCountByNumber",
  eth_getUncleCountByBlockHash: "eth_getUncleCountByBlockHash",
  eth_getUncleCountByBlockNumber: "eth_getUncleCountByBlockNumber",
  eth_getCode: "eth_getCode",
  eth_sign: "eth_sign",
  eth_call: "eth_call",
  eth_estimateGas: "eth_estimateGas",
  eth_getBlockByHash: "eth_getBlockByHash",
  eth_getBlockByNumber: "eth_getBlockByNumber",
  eth_getTransactionByHash: "eth_getTransactionByHash",
  eth_getTransactionByBlockHashAndIndex:
    "eth_getTransactionByBlockHashAndIndex",
  eth_getTransactionByBlockNumberAndIndex:
    "eth_getTransactionByBlockNumberAndIndex",
  eth_getTransactionReceipt: "eth_getTransactionReceipt",
  eth_getUncleByBlockHashAndIndex: "eth_getUncleByBlockHashAndIndex",
  eth_getUncleByBlockNumberAndIndex: "eth_getUncleByBlockNumberAndIndex",
  eth_newFilter: "eth_newFilter",
  eth_newBlockFilter: "eth_newBlockFilter",
  eth_newPendingTransactionFilter: "eth_newPendingTransactionFilter",
  eth_uninstallFilter: "eth_uninstallFilter",
  eth_getFilterChanges: "eth_getFilterChanges",
  eth_getFilterLogs: "eth_getFilterLogs",
  eth_getLogs: "eth_getLogs",
  eth_maxPriorityFeePerGas: "eth_maxPriorityFeePerGas",
  eth_sendRawTransaction: "eth_sendRawTransaction",
};

export enum HttpStatus {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLYHINTS = 103,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  AMBIGUOUS = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  I_AM_A_TEAPOT = 418,
  MISDIRECTED = 421,
  UNPROCESSABLE_ENTITY = 422,
  FAILED_DEPENDENCY = 424,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
}
