export const MantleGasOracleABI = [
  {
    type: "constructor",
    inputs: [{ type: "address", name: "_owner", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "IsBurning",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "charge",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "daGasPrice",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "daSwitch",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "decimals",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "gasPrice",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getL1Fee",
    inputs: [{ type: "bytes", name: "_data", internalType: "bytes" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getL1GasUsed",
    inputs: [{ type: "bytes", name: "_data", internalType: "bytes" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "l1BaseFee",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "overhead",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "renounceOwnership",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "scalar",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "sccAddress",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setCharge",
    inputs: [{ type: "uint256", name: "_charge", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setDAGasPrice",
    inputs: [{ type: "uint256", name: "_daGasPrice", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setDaSwitch",
    inputs: [{ type: "uint256", name: "_daSwitch", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setDecimals",
    inputs: [{ type: "uint256", name: "_decimals", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setGasPrice",
    inputs: [{ type: "uint256", name: "_gasPrice", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setIsBurning",
    inputs: [{ type: "uint256", name: "_isBurning", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setL1BaseFee",
    inputs: [{ type: "uint256", name: "_baseFee", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setOverhead",
    inputs: [{ type: "uint256", name: "_overhead", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setScalar",
    inputs: [{ type: "uint256", name: "_scalar", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "transferOwnership",
    inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
  },
  {
    type: "event",
    name: "ChargeUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "DAGasPriceUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "DASwitchUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "DecimalsUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "GasPriceUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "IsBurningUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "L1BaseFeeUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "OverheadUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { type: "address", name: "previousOwner", indexed: true },
      { type: "address", name: "newOwner", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ScalarUpdated",
    inputs: [{ type: "uint256", name: "", indexed: false }],
    anonymous: false,
  },
];
