name: Build binaries

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  binaries:
    name: Build skandha binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
          - os: skandha-arm64-runner
            platform: linux
            arch: arm64
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Install arm64 specifics
        run: |-
          # Install missing yarn
          # See https://github.com/github-early-access/arm-runners-beta/issues/5
          curl -fsSL --create-dirs -o $HOME/bin/yarn \
          https://github.com/yarnpkg/yarn/releases/download/v1.22.22/yarn-1.22.22.js
          chmod +x $HOME/bin/yarn
          echo "$HOME/bin" >> $GITHUB_PATH
          # Install missing build-essential
          sudo apt-get update
          sudo apt-get install -y build-essential
      - uses: "./.github/actions/setup-and-build"
        with:
          node: 20
      - run: |
          mkdir -p dist
          yarn global add caxa@3.0.1
          npx caxa -m "Unpacking skandha binary, please wait..." -D -p "yarn install --frozen-lockfile --production" --input . --output "skandha" -- "{{caxa}}/node_modules/.bin/node" "--max-old-space-size=8192" "{{caxa}}/node_modules/.bin/skandha"
          tar -czf "dist/skandha-${{ inputs.version }}-${{ matrix.platform }}-${{ matrix.arch }}.tar.gz" "skandha"
      - name: Upload binaries
        if: ${{ !github.event.act }} # skip during local actions testing
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: dist/
          if-no-files-found: error
