name: Build skandha unstable docker image 

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Get package version
        id: get_version
        run: echo version=$(git rev-parse --short "$GITHUB_SHA") >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/skandha:unstable
            ${{ secrets.DOCKERHUB_USERNAME }}/skandha:unstable-${{ steps.get_version.outputs.version }}
      -
        name: Create GitHub release
        uses: "marvinpinto/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "unstable"
          prerelease: true
          title: Release unstable-${{ steps.get_version.outputs.version }}
      - 
        name: Trigger dev pipeline
        run: ${{ secrets.PIPELINE_DEV_TRIGGER  }}
